# -*- coding: utf-8 -*-
# = gluon - component based web application framework
# == license
#   :include:../LICENSE
#

require 'gluon/controller'
require 'gluon/po'
require 'gluon/rs'
require 'rack'

module Gluon
  class Root
    def initialize(app)
      @app = app
    end

    # for debug
    def inner
      @app
    end

    def call(env)
      env[:gluon_root_script_name] = env['SCRIPT_NAME']
      @app.call(env)
    end
  end

  # = application for Rack
  class Application
    def initialize(logger, cmap, template_engine, service_man)
      @logger = logger
      @cmap = cmap
      @template_engine = template_engine
      @service_man = service_man
      @page_list = []
      @default_app = nil
    end

    def mount(page_type)
      @page_list.push [
        Controller.find_path_filter(page_type) || %r"^/?$",
        page_type
      ]
      nil
    end

    def run(app)
      @default_app = app
      nil
    end

    def find_page(path_info)
      for path_filter, page_type in @page_list
        if (path_info =~ path_filter) then
          path_args = $~.to_a
          path_args.shift
          return page_type, path_args
        end
      end

      nil
    end

    def call(env)
      # renew request object to refresh SCRIPT_NAME and PATH_INFO
      # generated by Rack::URLMap.
      env.delete('rack.request')

      r = RequestResponseContext.new(Rack::Request.new(env), Rack::Response.new)
      r.logger = @logger
      r.cmap = @cmap
      r.backend_service = @service_man.new_services

      page_type, r.path_args = find_page(r.equest.path_info)
      unless (page_type) then
        if (@default_app) then
          return @default_app.call(env)
        else
          raise "not found an application for `#{r.equest.url}'"
        end
      end

      r.esponse['Content-Type'] = "text/html; charset=#{page_type.page_encoding}"
      c = page_type.new
      r.controller = c
      c.r = r
      po = PresentationObject.new(c, r, @template_engine)
      page_result = nil

      c.page_around{
        c.page_start
        begin
          c.page_validation_preprocess
          Controller.set_form_params(c, r.equest.params)
          c.page_request(*r.path_args)
          if (action = Controller.find_first_action(c, r.equest.params)) then
            if (r.validation) then
              action.call
            else
              if (r.validation.nil?) then
                raise "not validated page of `#{c}'"
              end
            end
          end
          page_result = c.class.process_view(po)
        ensure
          c.page_end
        end
      }

      r.esponse.write(page_result)
      r.esponse.finish
    end
  end
end

# Local Variables:
# mode: Ruby
# indent-tabs-mode: nil
# End:
