# -*- coding: utf-8 -*-

# for idnet(1)
CVS_ID = '$Id$'

require 'rbconfig'
include RbConfig

base_dir = File.join(File.dirname(__FILE__), '..')

task :default => [ :test ]

task :test do
  cmds = [ "#{base_dir}/bin/gluon_local", '-d', base_dir, CONFIG['RUBY_INSTALL_NAME'], 'run.rb' ]
  cmds << ENV['TEST_OPTS'] if (ENV.key? 'TEST_OPTS')
  cmds << ENV['TEST_CASE'] if (ENV.key? 'TEST_CASE')
  ruby *cmds
end

task :clean do
  for erbc in Dir['*.erbc']
    rm_f erbc
  end
end

# Local Variables:
# mode: Ruby
# indent-tabs-mode: nil
# End:
