#!/usr/local/bin/ruby

# for ident(1)
CVS_ID = '$Id$'

require 'gluon'
require 'webrick'

base_dir = File.join(File.dirname($0), '..')
cgi_script = File.join(File.dirname($0), '..', 'cgi-bin', 'gluon.cgi')

options = {
  :base_dir => base_dir,
  :lib_dir => File.join(base_dir, 'lib'),
  :view_dir => File.join(base_dir, 'view'),
  :conf_path => File.join(base_dir, 'config.rb')
}

builder = Gluon::Builder.new(options)
builder.load_conf

server = WEBrick::HTTPServer.new(:Port => builder.port,
                                 :CGIInterpreter => 'ruby')

server.mount('/',
             WEBrick::HTTPServlet::CGIHandler,
             File.expand_path(cgi_script))

trap('INT') { server.shutdown }
server.start

# Local Variables:
# mode: Ruby
# indent-tabs-mode: nil
# End:
