# -*- coding: utf-8 -*-

load File.join(File.dirname(__FILE__), '.local_ruby_env')

def server(*options)
  [ 'rackup', '-I', get_project_libdir ] + options + get_command_options
end

desc 'alias for server_develop.'
task :server => [ :server_develop ]

desc 'start server for development (rackup options for o1, o2, ...).'
task :server_develop => [ :secret ] do
  ENV['GLUON_ENV'] = 'development'
  sh *server('-E', 'development')
end

desc 'start server for deployment (rackup options for o1, o2, ...).'
task :server_deploy => [ :secret ] do
  ENV['GLUON_ENV'] = 'deployment'
  sh *server('-E', 'deployment')
end

desc 'start CGI server.'
task :cgi_server => [ :secret ] do
  ruby *get_ruby_options, "#{get_project_dir}/bin/cgi_server"
end

desc 'make random secret for cookie based session.'
task :secret do
  secret = "#{get_project_dir}/secret"
  unless File.exist? secret then
    puts 'make random secret for cookie based session.'
    require 'digest'
    id = Digest::MD5.new
    now = Time.now
    id.update(now.to_s)
    id.update(now.usec.to_s)
    id.update(rand(0).to_s)
    id.update($$.to_s)
    id.update(Dir.getwd)
    File.open(secret, 'w:us-ascii') do |f|
      f.write id.hexdigest
    end
  end
end

desc 'clean garbage files'
task :clean do
  for f in Dir['**/*.erbc'] + Dir['*~']
    rm f
  end
end

desc 'alias for local_server_develop.'
task :local_server => [ :local_server_develop ]

desc 'start server for development (project local RubyGems repository).'
task :local_server_develop => [ :secret ] do
  ENV['GLUON_ENV'] = 'development'
  run_local_command *server('-E', 'development')
end

desc 'start server for deployment (project local RubyGems repository).'
task :local_server_deploy => [ :secret ] do
  ENV['GLUON_ENV'] = 'deployment'
  run_local_command *server('-E', 'deployment')
end

desc 'make CGI environment for project local RubyGems repository.'
task :local_cgi_env do
  cgi_env = "#{get_project_dir}/cgi.env"
  if File.exist? cgi_env then
    mv cgi_env, cgi_env + File.stat(cgi_env).mtime.strftime(".backup_%Y%m%d_%H%M%S")
  end
  File.open(cgi_env, 'w:us-ascii') do |f|
    f.puts '#!/bin/sh'
    f.puts 'RUBYOPT=rubygems; export RUBYOPT'
    f.puts 'GEM_HOME="$BASE_DIR/gems"; export GEM_HOME'
    f.puts 'PATH="$PATH:$GEM_HOME/bin"; export PATH'
    f.puts 'GLUON_ENV=deployment; export GLUON_ENV'
  end
end

# Local Variables:
# mode: Ruby
# indent-tabs-mode: nil
# End:
